# services:
#   generator:
#     build: ./generator
#     container_name: generator
#     environment:
#       KAFKA_BROKER_URL: kafka:9092
#       TRANSACTIONS_TOPIC: queueing.transactions
#       TRANSACTIONS_PER_SECOND: 1000
#     networks:
#       - kafka-network

#   detector:
#     build: ./detector
#     container_name: detector
#     environment:
#       KAFKA_BROKER_URL: kafka:9092
#       TRANSACTIONS_TOPIC: queueing.transactions
#       LEGIT_TOPIC: streaming.transactions.legit
#       FRAUD_TOPIC: streaming.transactions.fraud
#     networks:
#       - kafka-network

# networks:
#   kafka-network:
#     external: true
services:

  generator:
      build: ./generator
      container_name: generator
      environment:
        KAFKA_BROKER_URL: kafka:9092
        TRANSACTIONS_TOPIC: queueing.transactions
        TRANSACTIONS_PER_SECOND: 1000
      networks:
        - kafka-network

  detector:
    build: ./detector
    container_name: detector
    environment:
      KAFKA_BROKER_URL: kafka:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      LEGIT_TOPIC: streaming.transactions.legit
      FRAUD_TOPIC: streaming.transactions.fraud
    networks:
      - kafka-network

volumes:
  kafka_data:

networks:
  kafka-network:
    external: true