# version: "3.8"

# services:
#   kafka:
#     image: apache/kafka-native:latest
#     container_name: kafka
#     ports:
#       - "9092:9092"
#       - "9093:9093"
#     environment:
#       KAFKA_PROCESS_ROLES: "broker,controller"
#       KAFKA_NODE_ID: "1"
#       KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
#       KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
#       KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
#       KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
#       KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
#       KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#       KAFKA_LOG_DIRS: "/var/lib/kafka/data"
#     volumes:
#       - kafka-data:/var/lib/kafka/data
#     networks:
#       - kafka-network

# networks:
#   kafka-network:
#     external: true

# volumes:
#   kafka-data:
version: "3.8"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: "YhJjEzJRS4uKrTIUeHpcMw"
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - kafka-network

# Add UI Service

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - kafka-network



networks:
  kafka-network:
    external: true

volumes:
  kafka-data:
